services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app # Hot reload: changes in code update container instantly
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules # Prevents overwriting local node_modules
    depends_on:
      - backend
